### ISSUE TITLE
Quick fix Bug with parsing integer 127. Throws ArrayIndexOutOfBounds.

### ISSUE THREAD

**Issue by sid-parekar** [worldturner/medeia-validator#10]
Hi,
I am actively using this library. For one particular validation, it started throwing ArrayIndexOutOfBounds Exception. I've managed to root cause it to below line. 

Basically, when an integer has a value of 127, this will throw an IndexOutOfBoundsException. 

Apologies, that I did not submit a fix commit myself. I would've needed to checkout the package. Fix is simple, swap this line
`if (longValue >= minLongValue && longValue <= maxLongValue) {`
with this line:
`if (longValue >= minLongValue && longValue < maxLongValue) {`

https://github.com/worldturner/medeia-validator/blob/9f435c57f5a31cc5f7fbde6cdae747c38a2ed9ec/medeia-validator-core/src/main/kotlin/com/worldturner/medeia/parser/JsonTokenData.kt#L138

To reproduce the issue, use following Test Schema and Test Upload:

***Test Schema***
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "test schema",
  "properties": {
    "testNumber": {
      "type": "integer",
      "minimum": 0
    }
  }
}
```

***Test Upload***
```
{
  "testNumber": 127
}
```

**Comment by worldturner** [comment]
Will release new version later today

**Comment by worldturner** [comment]
Version 1.1.1 is released and available on maven-central
