### ISSUE TITLE
Name clash with https://github.com/medeia/medeia (my fault, not yours)

### ISSUE THREAD

**Issue by froth** [worldturner/medeia-validator#8]
Hi there,

I accidentally also started an open source project named medeia.
I am sorry that it happened. I did a (not very thorough) search if the name was already taken and found nothing.

But after pushing to sonatype I found your project and was annoyed with myself because I was not serious enough about finding duplicates before.

After I found out I was asking myself whether I would have to rename my project now. 
There a two points why I don't really want to do it:
 - Seems like a lot of work with travis-ci and sonatype and stuff
 - More important to me: the name is really fitting for my project and I do like it a lot: medeia is a scala functional programming library for decoding BSON. It is heavily inspired by the scala json library circe which is a fork of argonaut. So I was searching for a nice name also from the argonaut saga which starts with m (BSON is the data format of mongodb). And medeia was just the perfect fit.

**But** then I asked myself: What if it offends the author of the other project?
So here is my question: 
I will happily rename my project if it bothers you in any way, that it has the same name. Are you OK with our projects having the same name?

**Comment by worldturner** [comment]
Sure, go ahead.
